//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OScanWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbHammerspaceEntities : DbContext
    {
        public dbHammerspaceEntities()
            : base("name=dbHammerspaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assinatura> Assinatura { get; set; }
        public virtual DbSet<FileStore> FileStore { get; set; }
        public virtual DbSet<Maquina> Maquina { get; set; }
        public virtual DbSet<Memoria> Memoria { get; set; }
        public virtual DbSet<Processador> Processador { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
